### ISSUE TITLE
Video suggests likely cause of boltcard bricking

### ISSUE THREAD

**Issue by johnheenan** [boltcard/bolt-nfc-android-app#45]
Link to video with boltcard bricking at https://youtu.be/n3Vx8nFb4nk

By bricking I mean the boltcard cannot now be reset. I was able to withdraw funds.

Contrary to what is in text in the video, I think the likely cause of the bricking is a second setup on a card already in a setup state.

Rather ironically the solution looks like what I had suggested months ago: extra record keeping at the boltcard service end.

Most times a bricked cards won't even be recognised.

**Comment by johnheenan** [comment]
I have got console logs. The boltcard creator app was compiled from the current github source

![image](https://github.com/user-attachments/assets/46ecbfb2-a0fd-4a80-ab63-ffe1ceab5382)

![image](https://github.com/user-attachments/assets/a2924639-0632-42f6-af56-20a479d45203)

**Comment by johnheenan** [comment]
For this partcular bricking incident, what about a code change at the boltcard service (BTCPay Server) end that refuses to allow seup parameters for a card already known to be in a setup state? 

Instead provide a message that card must be reset first.

**Comment by NicolasDorier** [comment]
BTCPay can't read the card, only the boltcard can.
This is a very useful demo. I will try to repro on my side with proper logs to understand what is going on.

**Comment by NicolasDorier** [comment]
So I have an idea about what happens here:

You call Setup once before having Reset the previous cycle.
The Setup fails because it can't authenticate with the default key 00000.
The problem is that the boltcard app made a request to BTCPay Server, bumping the version on our side.

And now if you try to reset, BTCPay will send you the wrong keys, as the version has been bumped without the keys having changed on the device.

An easy fix on bolt-nfc-android-app would be to only request the keys to BTCPay if the authentication to 00000 have been successful.

**Comment by johnheenan** [comment]
The pull request at https://github.com/boltcard/bolt-nfc-android-app/pull/46 has been merged and a new Android release, v0.3.2,  is in the play store.

I have so far not been able to brick boltcards with the fix in place.
